### ISSUE TITLE
tsstats banned ?

### ISSUE THREAD

**Issue by ThatsPepe** [yugecin/tsstats#18]
I installed the script exactly according to the instructions and it always shows me the error in the nohup.out over time. Does anyone have an idea?

[6/12 20:56:00] <- error id=0 msg=ok
[6/12 20:56:01] -- updated: 6 queries in 587ms
[6/12 21:00:31] <- notifycliententerview cfid=0 ctid=46 reasonid=0 clid=15 client_unique_identifier=ServerQuery client_nickname=Unknown client_input_muted=0 client_output_muted=0 client_outputonly_muted=0 client_input_hardware=0 client_output_hardware=0 client_meta_data client_is_recording=0 client_database_id=9 client_channel_group_id=8 client_servergroups=1,19 client_away=0 client_away_message client_type=1 client_flag_avatar client_talk_power=75 client_talk_request=0 client_talk_request_msg client_description client_is_talker=0 client_is_priority_speaker=0 client_unread_messages=0 client_nickname_phonetic client_needed_serverquery_view_power=75 client_icon_id=0 client_is_channel_commander=0 client_country=DE client_channel_group_inherited_channel_id=46 client_badges client_myteamspeak_id client_integrations client_myteamspeak_avatar client_signed_badges
[6/12 21:00:31] <- notifyclientleftview cfid=46 ctid=0 reasonid=8 reasonmsg=disconnecting clid=15
[6/12 21:01:00] er Received null response. Is this serverquery user (temp) banned?
[6/12 21:01:00] er InterruptedException in job
-- -- sleep interrupted
 0 at java.base/java.lang.Thread.sleep(Native Method)
 1 at core.Job.run(Job.java:40)
[6/12 21:01:00] er out of loop, reconnecting after 180000

**Comment by ThatsPepe** [comment]
yes the server IP is added and b_client_ignore_antiflood is also active for the server group. I've also tried serveradmin access and it's the same there

**Comment by yugecin** [comment]
can you see in the log if this happens always after the same interval after the last time the bot sent a message to the server?

this might be the same that some other people experienced too, I'll see if I can work out something

**Comment by ThatsPepe** [comment]
Yes, the interval is always the same in the logs and I've also checked everything, only bant the server query permanently

**Comment by yugecin** [comment]
> only bant the server query permanently

I don't understand this part, did the serverquery really get banned permanently?

**Comment by yugecin** [comment]
hmm I'm out of ideas then 😕

**Comment by ThatsPepe** [comment]
I think I found the error because I forgot to download the tsstats.jar from the update and now it to be working with the new config

so far everything looks good ;)

[9/12 14:11:12] -- updated: 6 queries in 433ms
[9/12 14:11:27] -- Connected in 0 attempts
[9/12 14:16:07] -- updated: 6 queries in 548ms
[9/12 14:21:07] -- updated: 6 queries in 472ms
[9/12 14:26:07] -- updated: 6 queries in 551ms
[9/12 14:31:08] -- updated: 6 queries in 603ms
[9/12 14:36:07] -- updated: 6 queries in 481ms

**Comment by yugecin** [comment]
Nice!! :D
